project:
  type: website

website:
  title: "website"
  favicon: "maulwurf.png"
  sidebar:
    style: "docked"
    contents:
      - section: "Empirische Wirtschaftsforschung"
        contents:
          - ewf/ewf.qmd
          - ewf/ewf-uebungen.qmd
          - ewf/ewf-klausurvorbereitung.qmd
          - ewf/zeitreihenanalyse.qmd
          - ewf/methoden-der-ewf.qmd
      - section: "Fundamentals of Finance"
        contents: 
          - fofi/fundamentals_of_finance.qmd
          - fofi/cofi_I.qmd
          - fofi/household_finance.qmd
      - file: statistical-machine-learning/sml.qmd
        text: "Statistical Machine Learning" 

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true


