project:
  type: website

website:
  title: "website"
  navbar:
    left:
      - file: index.qmd
        text: "Home"
      - file: about.qmd
        text: "About"
      - file: ewf/ewf.qmd
        text: "EWF"
      - file: oekonometrische-methoden/oekonometrische-methoden.qmd
        text: "Ökonometrische Methoden"
      - file: statistical-machine-learning/sml.qmd
  sidebar:
    - title: "EWF"
      style: "docked"
      contents:
        - ewf/ewf.qmd
        - ewf/ewf-uebung-1.qmd
    - title: "Ökon. Methoden"
      style: "docked"
      contents:
        - oekonometrische-methoden/oekonometrische-methoden.qmd
        - oekonometrische-methoden/zeitreihenanalyse.qmd
        - oekonometrische-methoden/methoden-der-ewf.qmd


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true


