project:
  type: website

website:
  title: "website"
  navbar:
    left:
      #- file: index.qmd
      #  text: "Home"
      - file: about.qmd
        text: "About"
      - file: ewf/ewf.qmd
        text: "EWF & mehr"
      - file: statistical-machine-learning/sml.qmd
        text: "Statistical Machine Learning"
      - file: fofi/fundamentals_of_finance.qmd
        text: "Finance"
  sidebar:
    - title: "EWF"
      style: "docked"
      contents:
        - ewf/ewf.qmd
        - ewf/ewf-uebung-1.qmd
        - ewf/oekonometrische-methoden.qmd
        - ewf/zeitreihenanalyse.qmd
        - ewf/methoden-der-ewf.qmd
    - title: "FoFi"
      style: "docked"
      contents: 
        - fofi/fundamentals_of_finance.qmd
        - fofi/cofi_I.qmd
        - fofi/household_finance.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true


