project:
  type: website

website:
  title: "website"
  favicon: "maulwurf.png"
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - section: "Empirische Wirtschaftsforschung"
        contents:
          - ewf/ewf.qmd
          - ewf/ewf-uebungen.qmd
          - ewf/ewf-klausurvorbereitung.qmd
          - ewf/zeitreihenanalyse.qmd
          - ewf/methoden-der-ewf.qmd
      - section: "Fundamentals of Finance"
        contents: 
          - fofi/fundamentals_of_finance.qmd
          - fofi/cofi_I.qmd
          - fofi/household_finance.qmd
      - file: statistical-machine-learning/sml.qmd
        text: "Statistical Machine Learning" 
      - file: masterseminar/Auswertung.Rmd
        text: "Masterseminar"         
      - section: "Projekt Immobilienmarkt"
        contents: 
          - immoprojekt/uebersicht.Rmd
          - immoprojekt/git-tutorial.md
          - immoprojekt/cleaning.Rmd
          - immoprojekt/auswertung.Rmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true


