project:
  type: website

website:
  title: "website"
  navbar:
    left:
      - file: index.qmd
        text: "Home"
      - file: about.qmd
        text: "About"
      - file: ewf.qmd
        text: "EWF"
  sidebar:
    - title: "EWF"
      style: "docked"
      contents:
        - ewf.qmd
        - ewf-uebung-1.qmd


format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true


